[{"name": "test.test_solve_quadratic.SolveQuadratic.test_first", "status": "failed", "message": "2 != 0 within 4 places : 0.000000 is not a solution for equation 1.000000*x**2 + -3.000000*x + 2.000000 == 0!", "passed": false, "points": ["p01-08.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e08_solve_quadratic/test/test_solve_quadratic.py\", line 26, in test_first\n    self.assertAlmostEqual(a*x**2 + b*x + c, 0, places=4, msg=\"%f is not a solution for equation %s!\" % (x, eq))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 878, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_solve_quadratic.SolveQuadratic.test_random", "status": "failed", "message": "3.9819934817182956 != 0 within 4 places : 0.000000 is not a solution for equation 2.605524*x**2 + 8.927527*x + 3.981993 == 0!", "passed": false, "points": ["p01-08.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e08_solve_quadratic/test/test_solve_quadratic.py\", line 53, in test_random\n    self.assertAlmostEqual(a*x**2 + b*x + c, 0, places=4, msg=\"%f is not a solution for equation %s!\" % (x, eq))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 878, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_solve_quadratic.SolveQuadratic.test_second", "status": "failed", "message": "1 != 0 within 4 places : 0.000000 is not a solution for equation 1.000000*x**2 + 2.000000*x + 1.000000 == 0!", "passed": false, "points": ["p01-08.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e08_solve_quadratic/test/test_solve_quadratic.py\", line 34, in test_second\n    self.assertAlmostEqual(a*x**2 + b*x + c, 0, places=4, msg=\"%f is not a solution for equation %s!\" % (x, eq))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 878, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_solve_quadratic.SolveQuadratic.test_third", "status": "failed", "message": "1 != 0 within 4 places : 0.000000 is not a solution for equation -2.000000*x**2 + 2.000000*x + 1.000000 == 0!", "passed": false, "points": ["p01-08.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e08_solve_quadratic/test/test_solve_quadratic.py\", line 42, in test_third\n    self.assertAlmostEqual(a*x**2 + b*x + c, 0, places=4, msg=\"%f is not a solution for equation %s!\" % (x, eq))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 878, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}]