[{"name": "test.test_reverse_dictionary.ReverseDictionary.test_first", "status": "failed", "message": "'move' != ['move'] : Incorrect translation of 'liikuttaa' for dict {'move': ['liikuttaa'], 'hide': ['piilottaa', 'salata']}!", "passed": false, "points": ["p01-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e13_reverse_dictionary/test/test_reverse_dictionary.py\", line 21, in test_first\n    self.assertEqual(r[\"liikuttaa\"], [\"move\"], msg=\"Incorrect translation of 'liikuttaa' for dict %s!\" % sd)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_reverse_dictionary.ReverseDictionary.test_second", "status": "failed", "message": "'move' != ['move'] : Incorrect translation of 'liikuttaa' for dict {'move': ['liikuttaa'], 'hide': ['piilottaa', 'salata'], 'six': ['kuusi'], 'fir': ['kuusi']}!", "passed": false, "points": ["p01-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e13_reverse_dictionary/test/test_reverse_dictionary.py\", line 30, in test_second\n    self.assertEqual(r[\"liikuttaa\"], [\"move\"], msg=\"Incorrect translation of 'liikuttaa' for dict %s!\" % sd)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]