[{"name": "test.test_merge.Merge.test_calls", "status": "passed", "message": "", "passed": true, "points": ["p01-09.1"], "backtrace": []}, {"name": "test.test_merge.Merge.test_first", "status": "failed", "message": "Lists differ: [] != [1, 2, 5, 6, 9, 10, 12]\n\nSecond list contains 7 additional elements.\nFirst extra element 0:\n1\n\n- []\n+ [1, 2, 5, 6, 9, 10, 12] : Not correct result for input lists [1, 5, 9, 12] and [2, 6, 10]!", "passed": false, "points": ["p01-09.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e09_merge/test/test_merge.py\", line 32, in test_first\n    self.assertEqual(result, sorted(L1+L2), msg=\"Not correct result for input lists %s and %s!\" % (L1,L2))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_merge.Merge.test_non_mutating", "status": "passed", "message": "", "passed": true, "points": ["p01-09.1"], "backtrace": []}, {"name": "test.test_merge.Merge.test_random", "status": "failed", "message": "0 != 30 : Incorrect length of result list for input lists [-100, -92, -58, -49, -39, -22, 6, 17, 23, 35, 36, 44, 59, 60, 71, 76, 80, 85, 89, 97] and [-77, -56, -34, -27, -23, -3, 0, 27, 31, 62]!", "passed": false, "points": ["p01-09.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e09_merge/test/test_merge.py\", line 46, in test_random\n    self.assertEqual(len(result), len(L), msg=\"Incorrect length of result list for input lists %s and %s!\" % (L1, L2))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]