[{"name": "test.test_vector_angles.VectorAngles.test_first", "status": "errored", "message": "ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e15_vector_angles/test/test_vector_angles.py\", line 26, in test_first\n    err_msg=\"Incorrect result for vectors %s and %s!\" % (A, B))\n", "  File \"/usr/lib/python3/dist-packages/numpy/testing/utils.py\", line 1395, in assert_allclose\n    verbose=verbose, header=header, equal_nan=equal_nan)\n", "  File \"/usr/lib/python3/dist-packages/numpy/testing/utils.py\", line 761, in assert_array_compare\n    val = comparison(x, y)\n", "  File \"/usr/lib/python3/dist-packages/numpy/testing/utils.py\", line 1390, in compare\n    equal_nan=equal_nan)\n", "  File \"/usr/lib/python3/dist-packages/numpy/core/numeric.py\", line 2538, in isclose\n    xfin = isfinite(x)\n"]}, {"name": "test.test_vector_angles.VectorAngles.test_main", "status": "failed", "message": "0 not greater than or equal to 1 : You should call the vector_angles function from the main function!", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e15_vector_angles/test/test_vector_angles.py\", line 33, in test_main\n    msg=\"You should call the vector_angles function from the main function!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1227, in assertGreaterEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_vector_angles.VectorAngles.test_zero", "status": "errored", "message": "ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e15_vector_angles/test/test_vector_angles.py\", line 40, in test_zero\n    err_msg=\"Incorrect result for vectors %s and %s!\" % (A, A))\n", "  File \"/usr/lib/python3/dist-packages/numpy/testing/utils.py\", line 1395, in assert_allclose\n    verbose=verbose, header=header, equal_nan=equal_nan)\n", "  File \"/usr/lib/python3/dist-packages/numpy/testing/utils.py\", line 761, in assert_array_compare\n    val = comparison(x, y)\n", "  File \"/usr/lib/python3/dist-packages/numpy/testing/utils.py\", line 1390, in compare\n    equal_nan=equal_nan)\n", "  File \"/usr/lib/python3/dist-packages/numpy/core/numeric.py\", line 2538, in isclose\n    xfin = isfinite(x)\n"]}]