[{"name": "test.test_file_extensions.FileExtensions.test_calls", "status": "failed", "message": "Expected 'open' to have been called once. Called 0 times.", "passed": false, "points": ["p02-07.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e07_file_extensions/test/test_file_extensions.py\", line 30, in test_calls\n    o.assert_called_once()\n", "  File \"/usr/lib/python3.6/unittest/mock.py\", line 795, in assert_called_once\n    raise AssertionError(msg)\n"]}, {"name": "test.test_file_extensions.FileExtensions.test_first", "status": "failed", "message": "Lists differ: [] != ['test']\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n'test'\n\n- []\n+ ['test'] : There should be exactly one filename without an extension!", "passed": false, "points": ["p02-07.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e07_file_extensions/test/test_file_extensions.py\", line 23, in test_first\n    msg=\"There should be exactly one filename without an extension!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_file_extensions.FileExtensions.test_main", "status": "failed", "message": "0 != 1 : You should call function 'file_extensions' from main!", "passed": false, "points": ["p02-07.2"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e07_file_extensions/test/test_file_extensions.py\", line 37, in test_main\n    msg=\"You should call function 'file_extensions' from main!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]