[{"name": "test.test_sum_equation.SumEquation.test_empty", "status": "failed", "message": "'' != '0 = 0'\n+ 0 = 0 : Incorrect result for an empty input list!", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e19_sum_equation/test/test_sum_equation.py\", line 37, in test_empty\n    self.assertEqual(result, \"0 = 0\", msg=\"Incorrect result for an empty input list!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_sum_equation.SumEquation.test_first", "status": "failed", "message": "'' != '1 + 5 + 7 = 13'\n+ 1 + 5 + 7 = 13 : Incorrect result for input list [1, 5, 7]!", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e19_sum_equation/test/test_sum_equation.py\", line 22, in test_first\n    self.assertEqual(result, \"1 + 5 + 7 = 13\", msg=\"Incorrect result for input list %s!\" % L)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_sum_equation.SumEquation.test_random", "status": "failed", "message": "None is not true", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e19_sum_equation/test/test_sum_equation.py\", line 28, in test_random\n    self.assertTrue(m)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\n"]}]