[{"name": "test.test_interleave.Interleave.test_calls", "status": "failed", "message": "Expected 'zip' to have been called once. Called 0 times.", "passed": false, "points": ["p01-11.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e11_interleave/test/test_interleave.py\", line 45, in test_calls\n    pzip.assert_called_once()\n", "  File \"/usr/lib/python3.6/unittest/mock.py\", line 795, in assert_called_once\n    raise AssertionError(msg)\n"]}, {"name": "test.test_interleave.Interleave.test_first", "status": "failed", "message": "Lists differ: [] != [1, 20, 'a', 2, 30, 'b', 3, 40, 'c']\n\nSecond list contains 9 additional elements.\nFirst extra element 0:\n1\n\n- []\n+ [1, 20, 'a', 2, 30, 'b', 3, 40, 'c'] : Incorrect result for input lists [1, 2, 3], [20, 30, 40], ['a', 'b', 'c']!", "passed": false, "points": ["p01-11.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e11_interleave/test/test_interleave.py\", line 25, in test_first\n    self.assertEqual(result, [1, 20, 'a', 2, 30, 'b', 3, 40, 'c'], msg=\"Incorrect result for input lists %s, %s, %s!\" % (L1, L2, L3))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_interleave.Interleave.test_random", "status": "failed", "message": "0 != 200 : Incorrect result list length!", "passed": false, "points": ["p01-11.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e11_interleave/test/test_interleave.py\", line 35, in test_random\n    self.assertEqual(len(result), n * size, msg=\"Incorrect result list length!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]