[{"name": "test.test_most_frequent_first.MostFrequentFirst.test_content", "status": "failed", "message": "1 not greater than or equal to 2 : Result\n[[0 4 4 7 5 2 1 5 2 8]\n [1 3 0 2 4 5 8 6 5 1]\n [2 7 3 7 5 8 3 0 5 9]\n [3 9 9 9 1 6 3 4 7 6]\n [3 2 4 5 8 7 4 0 2 7]\n [4 5 6 6 0 9 0 0 9 0]\n [5 6 3 4 8 3 7 4 5 8]\n [6 1 0 6 8 7 7 3 5 8]\n [8 7 7 2 6 5 7 7 4 7]\n [8 5 0 9 4 3 5 3 0 1]] not correctly sorted according to column 0!", "passed": false, "points": ["p03-03.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part03-e03_most_frequent_first/test/test_most_frequent_first.py\", line 46, in test_content\n    msg=\"Result\\n%s not correctly sorted according to column %i!\" % (result,c))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1227, in assertGreaterEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_most_frequent_first.MostFrequentFirst.test_same_rows", "status": "passed", "message": "", "passed": true, "points": ["p03-03.1"], "backtrace": []}]